version: '3.1'

services:
  redis:
    image: redis:7-alpine
    restart: always
    logging:
      driver: none

  mongo:
    image: mongo:6
    restart: always
    volumes:
      - ./mongo_data/mongodb:/data/db
    command: --quiet
    logging:
      driver: none
    ports:
      - "127.0.0.1:27017:27017"

  meili:
    image: getmeili/meilisearch:v1.0.2
    restart: always
    environment:
      - MEILI_HTTP_PAYLOAD_SIZE_LIMIT=1073741824 #1GiB
    volumes:
      - meilisearch_data:/meili_data

  mysql:
    image: ubuntu/mysql:8.0-22.04_beta
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    logging:
      driver: none
    command: "--skip-log-bin --default-authentication-plugin=mysql_native_password"

  bot:
    image: bennythink/yyetsbot
    depends_on:
      - redis
      - mongo
    restart: always
    env_file:
      - env/yyets.env

  web:
    image: bennythink/yyetsbot
    restart: always
    env_file:
      - env/yyets.env
    depends_on:
      - mongo
      - redis
      - mysql
    working_dir: /YYeTsBot/yyetsweb/
    volumes:
      - ./subtitle_data:/YYeTsBot/yyetsweb/subtitle_data
    command: [ "python3","server.py","-h=0.0.0.0" ]
    ports:
      - "127.0.0.1:8888:8888"
      - "172.17.0.1:8888:8888"


volumes:
  meilisearch_data:
